#21 Add a map screen to the app
DIT112-V19/group-04 pull request #23
Opened 2019-05-03 12:21 UTC by ih8c01d

# Description
 Add custom map screen. Add a compass. Add a user tracking button

Fixes  issue #21 

# How Has This Been Tested?

Tested on a simulator as well as a real-device

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code

2019-05-06 13:11 UTC, bartekspitza commented
The map looks good but nothing happens when you press a point on the map. I think we should implement this before merging into master. Ideally, when you press somewhere, it should mark the point on the map, and maybe send the coordinates (cartesian) to the server.

2019-05-06 13:14 UTC, bartekspitza requested changes
The map looks good but nothing happens when you press a point on the map. I think we should implement this before merging into master. Ideally, when you press somewhere, it should mark the point on the map, and maybe send the coordinates (cartesian) to the server.

2019-05-06 14:16 UTC, ih8c01d commented
This branch resolved issue #21. Adding map items is issue #22 which is being resolved on its separate branch.

2019-05-07 13:20 UTC, bartekspitza approved these changes

2019-05-07 13:21 UTC, merged