#87 addition of .travis.yml file
DIT112-V19/group-04 pull request #88
Opened 2019-08-24 15:49 UTC by WalrusArtist

The travis.yml file is required in order to accompany continuous integration using travisCI

2019-08-24 16:05 UTC, platisd commented
I'd say add everything in the same pull request and let me know when it's ready. Feel free to ask for help or feedback when you need it.

2019-08-24 16:28 UTC, WalrusArtist commented
I see. I was wondering why I'm unable to see that my repository is running after I have added the yml file on travis. It is stated that I have no builds for the repository.

2019-08-24 16:40 UTC, platisd commented
Rename the configuration file to `.travis.yml`. You've got an extra "a" in the file name. :+1:

2019-08-24 17:49 UTC, WalrusArtist commented
@platisd I have updated my yml file but travis seems to only detect my previous commit rather than my last one. How do I make it so that it detects my last commit?

2019-08-24 18:36 UTC, platisd commented on arduino/obstacleAvoidance/obstacleAvoidance.ino
> -#include <Smartcar.h>
I don't think removing this library will help you compile this sketch! :grin:

2019-08-30 12:46 UTC, platisd commented
Remove that `.yaml` file completely and see if anything changes

2019-08-30 14:00 UTC, WalrusArtist commented
@platisd I have been trying to test my ladder commits and had found out that travis couldn't parse any of them. I looked around and found out that it could be due to indentation problems (using tabs over spaces). I had converted to spaces using Atom and Sublime with no luck. I am unable to detect my fault at this point.

<img width="891" alt="Screenshot 2019-08-30 at 14 42 35" src="https://user-images.githubusercontent.com/48831035/64026288-c2e96f80-cb3e-11e9-9c5e-e6955e339f08.png">

2019-08-30 14:06 UTC, platisd commented
Can you send me a link to the actual logs of the failed build because I can't find them?

2019-08-31 10:04 UTC, platisd commented
@WalrusArtist the commit I just pushed fixes any formatting errors (actually I didn't understand why Travis was unhappy with what you had but anyway) among some other smaller mistakes. See the commit's description and contents for more details.

In any case, now it builds the Python and the Arduino layers of the project. This means that the first requirement of the re-exam is fulfilled. There's still an error with the app, which I am have no idea how to solve since i'm clueless about anything iOS. If it gives you too much trouble just remove building the application and focus on deploying the Arduino app as a release.

2019-08-31 15:05 UTC, WalrusArtist commented
> deploying the Arduino app as a release.

@platisd Would TestFlight be enough for this? If you're not familiar with what it is, it's basically an air-to-air deployment service for client testings provided by Apple.

2019-08-31 15:11 UTC, platisd commented
> > deploying the Arduino app as a release.
> 
> @platisd Would TestFlight be enough for this? If you're not familiar with what it is, it's basically an air-to-air deployment service for client testings provided by Apple.

Hmmm, I'm not sure how TestFlight works. I'd like a compiled version of one component of the system (aside the python script) to become available automatically every time something gets merged to `master`.
If this TestFlight can do that it's good with me.

2019-08-31 15:13 UTC, platisd commented
The easiest way as far as I'm concerned is to do that via the Github releases. Any other way that works is good enough for me.

2019-08-31 18:47 UTC, WalrusArtist commented
@platisd To obtain the hex file I would need to compile the .ino file. And for some reason i'm getting an error that states that there's no such file or directory "Smartcar.h". I'm unaware of why this is.

2019-08-31 19:07 UTC, WalrusArtist commented
Never mind, I just found out for some reason the library wasn't installed anymore

> @platisd To obtain the hex file I would need to compile the .ino file. And for some reason i'm getting an error that states that there's no such file or directory "Smartcar.h". I'm unaware of why this is.

2019-08-31 19:11 UTC, platisd commented
Not sure what you saw but since the build didn't fail the sketches were built.
Now you'll have to figure out where the compiled sketch ends up, point the deployed `file` field there and you'll be done I believe.

2019-08-31 19:49 UTC, WalrusArtist commented
@platisd I was not able to obtain the hex filing using Serial1 from obstacleAvoidance, and Serial3 from testCar. Changed both to Serial and they both compiled successfully resulting along the hex file. I hope this is okay

2019-08-31 19:56 UTC, platisd commented
No, its not OK to make changes in the logic so to make the build pass. :stuck_out_tongue:
What is the error exactly?

2019-08-31 20:06 UTC, WalrusArtist commented
Fair enough :) the error seems to be a basic declaration one. I'm not sure if it's due to a library I am missing, or maybe my Arduino version? Attached is a screenshot 

<img width="1234" alt="Screenshot 2019-08-31 at 21 58 29" src="https://user-images.githubusercontent.com/48831035/64068652-54d6a280-cc3b-11e9-873e-186259c830ea.png">

2019-08-31 20:10 UTC, platisd commented
OK I see. You're trying to compile this on your machine. Well, you have to choose "Arduino Mega" as your board. On CI it builds correctly since the `mega2560` argument is passed to `build_platform`.

The directories you're trying to find the hex files seem "temporary". How did you find out about them?

2019-08-31 20:41 UTC, platisd requested changes

2019-08-31 20:41 UTC, platisd commented on arduino/testCar/testCar.ino
Don't forget this one

2019-08-31 20:45 UTC, WalrusArtist commented
> The directories you're trying to find the hex files seem "temporary". How did you find out about them?

@platisd In the Arduino IDE selecting Sketch > Export Compiled Binary, and looking at the third line of the transactions in the compiler was the only the hex file i could find. 

I changed it to mega and it compiled successfully, and I got the hex files. Are you saying these hex files won't do because they're also temporary?

2019-08-31 20:46 UTC, WalrusArtist commented
> > The directories you're trying to find the hex files seem "temporary". How did you find out about them?
> 
> @platisd In the Arduino IDE selecting Sketch > Export Compiled Binary, and looking at the third line of the transactions in the compiler was the only the hex file i could find.
> 
> I changed it to mega and it compiled successfully, and I got the hex files. Are you saying these hex files won't do because they're also temporary?

FYI, the paths were the same so i didn't need to reedit the yaml file

2019-08-31 20:56 UTC, platisd commented
OK, then these file paths are most likely wrong. I I suspect that the hex files might be in the same folder. Try printing looking for them with something like `find . -iname "*.hex* 2>/dev/null` after you run the build step to see if you can locate them in your workspace.

2019-08-31 21:30 UTC, platisd requested changes

2019-08-31 21:30 UTC, platisd commented on .travis.yml
> +    - /arduino/testCar/testCar.ino.mega.hex
These two paths look wrong. You should probably add `$TRAVIS_BUILD_DIR` in front of them.

2019-09-01 12:52 UTC, platisd commented
Yeah, apparently the [CI script from Adafruit](https://github.com/adafruit/travis-ci-arduino) does not preserve the `.hex` or any other temporary files created during compilation. I made a [modified version](https://github.com/platisd/travis-ci-arduino) of it (which I will try to get merged with the Adafruit one) which does keep them.

The configuration now should be ready to be merged.
Please squash the commits before merging them so you don't flood the git history! (i.e. don't click on "Merge pull request" but on the arrow next to it and choose the appropriate option)
To test everything out after you have merged this, [create a new release](https://github.com/DIT112-V19/group-04/releases/new).

2019-09-01 12:54 UTC, platisd requested changes
Last thing you need to do:
* Remove `app/CarInterface.xcodeproj/project.xcworkspace/xcuserdata/kardodastin.xcuserdatad/UserInterfaceState.xcuserstate`

2019-09-01 21:34 UTC, platisd approved these changes
Good job

2019-09-01 22:20 UTC, merged