Basic app and server
DIT112-V19/group-04 pull request #9
Opened 2019-04-09 13:22 UTC by KalleHallden

2019-04-09 13:23 UTC, WalrusArtist submitted a review, later dismissed

2019-04-09 17:48 UTC, platisd requested changes
What story does this pull request solve or is related to? Please specify in the pull request description so we can achieve full traceability.

2019-04-10 14:00 UTC, konradotto commented
Edited the description adding a link to the issue (don't see a way of linking issues directly, only milestones)

2019-04-10 17:31 UTC, platisd commented
> Edited the description adding a link to the issue (don't see a way of linking issues directly, only milestones)

Do you mean you cannot write that it "relates to #3"? :grin:

2019-04-30 11:23 UTC, closed without merging